[package]
name = "cve-2019-16278"
version = "0.1.0"
authors = ["kali"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
